### ISSUE TITLE
French regions should not be in the country list.

### ISSUE THREAD

**Issue by steffenix** [i-rocky/country-list-js#13]
French regions should not be a specific country but just FR.
DOM:

French Guiana -> https://en.wikipedia.org/wiki/ISO_3166-2:GF

Guadeloupe -> https://en.wikipedia.org/wiki/ISO_3166-2:GP

Martinique -> https://en.wikipedia.org/wiki/ISO_3166-2:MQ

Réunion -> https://en.wikipedia.org/wiki/ISO_3166-2:RE

Mayotte -> https://en.wikipedia.org/wiki/ISO_3166-2:YT

and
COM:

French Polynesia -> https://en.wikipedia.org/wiki/ISO_3166-2:PF

Saint Pierre et Miquelon -> https://en.wikipedia.org/wiki/ISO_3166-2:PM

Wallis and Futuna -> https://en.wikipedia.org/wiki/ISO_3166-2:WF

Saint Martin -> https://en.wikipedia.org/wiki/ISO_3166-2:MF

Saint Barthelemy -> https://en.wikipedia.org/wiki/ISO_3166-2:BL

**Comment by ekkis** [comment]
yes, I see you are correct.  what is DOM and COM? I will try to fix when I have the time

**Comment by steffenix** [comment]
DOM is for Overseas departments of France
TOM is Overseas territories of France

**Comment by ekkis** [comment]
the first link you shared states: "defines codes for the names of the principal subdivisions (e.g., provinces or states) of all countries coded in ISO 3166-1" i.e. country codes are defined in 3166-1.  in this code you'll find GP for Guadaloupe, which means that as far as ISO is concerned, Guadaloupe is a country.  this seems to apply to both DOM and COM

in fact, the classification includes a field for "independence", which for DOM/COM is marked as "no"... so at best I could encumber the model with this information but if I did that I'd need to do it for all the other countries, and I'd need to think about how to best represent this information

frankly, I disagree with the decision of the committee to classify these areas as countries, but it is what it is

I'm going to close this issue for now as WON'T FIX, but if you want to make a coherent argument for fixing it, please just reopen
