### ISSUE TITLE
Json hasn't all states for countries

### ISSUE THREAD

**Issue by OlgaMatosova** [i-rocky/country-list-js#2]

**Comment by i-rocky** [comment]
What exactly are you looking for?

![screenshot_2](https://user-images.githubusercontent.com/12933820/42202978-347479c4-7ebf-11e8-9183-5dbc613f4573.png)

**Comment by ekkis** [comment]
it would be useful also to have a Region... e.g. Sweden = Scandinavia, France = Continental Europe, Poland = Eastern Europe

**Comment by ekkis** [comment]
I'd be happy to code it up if you'll accept it

**Comment by ekkis** [comment]
I know what Olga is asking for here: a list of the 50 states in the US... this is an interesting endeavour and of largish scope because it means listing prefectures in Japan, Oblasts in Russia, Territories in Austrialia... which also begs the question of how far down to go.  there are provinces within regions, states within territories etc

would you be interested in collaborating on this? I've wanted to implement a solution for this for rather a while.  it also comes with a nomenclatures issue, what you call these political subdivisions

**Comment by ekkis** [comment]
I've posted a pull request for a first-pass implementation at regions.  states are more difficult.  I will attempt at some later point

**Comment by ekkis** [comment]
I should also mention that the CIA also has its own classification of world regions but that would be additional work

**Comment by ekkis** [comment]
I've made the enhancement (added provinces) but I've also broken the API.  if you care to merge, have a look at what I've done (currently published on NPM as ekkis-country-list-js):

https://github.com/ekkis/country-list-js

**Comment by i-rocky** [comment]
Sorry I haven't been able to reply. I'm catching up a deadline, and the deadline is today.
I"ll try merging tomorrow.

**Comment by i-rocky** [comment]
I wish I could clean my codes like you did.

**Comment by ekkis** [comment]
oh.  that's music to my ears.  I will generate a pull request.  this change does represent an IBC.  do you think it's worth the effort to provide backward compatibility?

**Comment by i-rocky** [comment]
Well, if we bump up a major version, we may not need back-compatibility. What do you say?

**Comment by ekkis** [comment]
that's true.  the PR is ready.  it needs to be merged

**Comment by ekkis** [comment]
any thought as to when you might accept the pull request? I want to pull my temporary package out of NPM

**Comment by i-rocky** [comment]
Sorry about the delay. I hurt my leg real bad, haven't been sitting on desktop unless it's urgent.
Pull request merged.

**Comment by ekkis** [comment]
sorry to hear mate.  take good care of it and thanks for the merge
