### ISSUE TITLE
Enhancement request: Search by dialling code

### ISSUE THREAD

**Issue by ekkis** [i-rocky/country-list-js#3]
it'd be awesome to to be able to search by dialling code.  In fact, it'd be even better to be able to feed the find method a phone number and have it deduce the country

**Comment by ekkis** [comment]
I'll code it up and submit a PR

**Comment by ekkis** [comment]
also, any objection to exporting the functions by name so I can do `.findByCapital()` instead of `.find(..., .FIND_BY_CAPITAL)`? it's more friendly

**Comment by ekkis** [comment]
PR submitted

**Comment by i-rocky** [comment]
Thank you

**Comment by ekkis** [comment]
would you be ok if I modified the code to expose the underlying methods?
