### ISSUE TITLE
The package doesn't support TypeScript

### ISSUE THREAD

**Issue by EliasSalom** [i-rocky/country-list-js#39]
the package doesn't support Typescript
I tried to run the package on react project and then I received and typescript error,
it shows the `code` property and it doesn't exist in the object, and when I tried to go to the property directly it showed in error

![image](https://user-images.githubusercontent.com/39850311/208095277-c2c76920-c0f0-44bf-bbee-8144b3d0e337.png)
![image](https://user-images.githubusercontent.com/39850311/208095359-256ba6f1-be23-49bc-b1d9-a264b431d7e0.png)
![image](https://user-images.githubusercontent.com/39850311/208095476-1b97813e-6b1a-4a82-a001-ef7e93eaab3a.png)

**Comment by ekkis** [comment]
https://ekkis.medium.com/this-was-my-first-experience-with-typescript-21e252a38965

**Comment by i-rocky** [comment]
https://snyk.io/advisor/npm-package/@types/country-list-js

**Comment by ekkis** [comment]
> https://snyk.io/advisor/npm-package/@types/country-list-js

is that something we should include in the package? I don't really know anything about TypeScript

**Comment by i-rocky** [comment]
When you add this as devDependwncy and our package as dependency, this one is used as types resolver.
