### ISSUE TITLE
Make it clearer on how to use on the web with country.min.js

### ISSUE THREAD

**Issue by NeedNot** [i-rocky/country-list-js#56]
where does the country variable come from
ive also tried importing as a module and still no luck

**Comment by ekkis** [comment]
the country variable holds the module itself.  as indicated on the README:
```
// using ES6 modules

import country from 'country-list-js';

// using CommonJS modules
var country = require('country-list-js'); 
```

**Comment by NeedNot** [comment]
> the country variable holds the module itself. as indicated on the README:
> 
> ```
> // using ES6 modules
> 
> import country from 'country-list-js';
> 
> // using CommonJS modules
> var country = require('country-list-js'); 
> ```

just gives me an error saying there is no default module export

**Comment by ekkis** [comment]
I provided 2 modalities.  if one doesn't work for you, try the other
