### ISSUE TITLE
Missing phone country codes? eg AC/+247 (ascension island)

### ISSUE THREAD

**Issue by unilynx** [i-rocky/country-list-js#62]
I was seeing whether I could swap out libphonenumber-js (https://gitlab.com/catamphetamine/libphonenumber-js) for the phone.json datafile (as I only need the dialing codes and not the full formats).

But there appears to be a difference in the actual data. Eg, libphonenumber-js lists Ascension Island (AC, country code 247) here: https://gitlab.com/catamphetamine/libphonenumber-js/-/blob/master/PhoneNumberMetadata.xml?ref_type=heads#L104 but AC is not in `data/phone.json`

Is this intentional (is country-list-js limited in scope) or is this just some missing data?

**Comment by ekkis** [comment]
it's just missing data.  please feel free to submit a PR.  I will approve it

**Comment by unilynx** [comment]
Only two were missing, AC and TA. Wouldn't have noticed if AC wasn't alphabetically first..
